services:
  db:
    image: postgres:16
    container_name: Museum_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: Museumdb
      POSTGRES_USER: Museumuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - Museum_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Museumuser -d Museumdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  Museum_data: